setup:
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	brew install difftastic fd fzf git kubectl kubectx kube-ps1 rg tmux watch
	curl https://sh.rustup.rs -sSf | sh
	cargo install eza
	cargo install atuin
