setup:
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	brew install difftastic fzf kubectl kubectx kube-ps1 tmux git
	curl https://sh.rustup.rs -sSf | sh
	cargo install eza
	cargo install atuin
