
[font]
size = 7

[selection]
save_to_clipboard = true

[window]
decorations = "none"

[terminal.shell]
program = "/usr/bin/tmux"

[general]
import = ["/home/drmorr/.config/alacritty/themes/remedy-dark.toml"]
