
[font]
size = 7

[font.normal]
family = "Maple Mono"

[selection]
save_to_clipboard = true

[window]
decorations = "none"

[terminal.shell]
program = "/usr/bin/tmux"

[cursor]
blink_timeout = 0

[general]
import = ["/home/drmorr/.config/alacritty/themes/remedy-dark.toml"]
