
colors.bright.black = '0x373b41'
colors.bright.blue = '0x81a2be'
colors.bright.cyan = '0x8abeb7'
colors.bright.green = '0xb5bd68'
colors.bright.magenta = '0xb294bb'
colors.bright.red = '0xcc6666'
colors.bright.white = '0xc5c8c6'
colors.bright.yellow = '0xf0c674'
colors.cursor.cursor = '0xf9e7c4'
colors.cursor.text = '0xf9e7c4'
colors.hints.end.background = '#fffaf3'
colors.hints.end.foreground = '#9893a5'
colors.hints.start.background = '#fffaf3'
colors.hints.start.foreground = '#797593'
colors.line_indicator.background = 'None'
colors.line_indicator.foreground = 'None'
colors.normal.black = '0x282a2e'
colors.normal.blue = '0x5f819d'
colors.normal.cyan = '0x5e8d87'
colors.normal.green = '0x8c9440'
colors.normal.magenta = '0x85678f'
colors.normal.red = '0xa54242'
colors.normal.white = '0x707880'
colors.normal.yellow = '0xde935f'
colors.primary.background = '0x2c2b2a'
colors.primary.foreground = '0xf9e7c4'
colors.primary.bright_foreground = '0x1C1508'
colors.primary.dim_foreground = '0x685E4A'
colors.selection.background = '0xdfdad9'
colors.selection.text = '0x575279'
colors.vi_mode_cursor.cursor = '0xcecacd'
colors.vi_mode_cursor.text = '0x575279'
font.size = 7
font.normal.family = 'Hack Nerd Font Mono'
selection.save_to_clipboard = true
shell.program = '/usr/bin/tmux'
window.decorations = 'none'
